name: Build zip on issue comment

on:
  issue_comment:
    types: [created]

env:
  PAGES_URL: https://alyip98.github.io/GH-Actions-Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout utilities
        uses: actions/checkout@v2
        with:
          repository: alyip98/GH-Actions-Test
          path: util

      - name: Print github event variable
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo "$EVENT"

      - name: Extract variables
        id: getvars
        uses: ./util/actions/extract-comment
        with:
          event: ${{ toJSON(github.event) }}

      - name: Print extracted variables
        run: echo "${{ steps.getvars.outputs.path }}" "${{ steps.getvars.outputs.version }}"

      - name: Checkout selected Markbind version
        uses: actions/checkout@v2
        with:
          repository: MarkBind/markbind
          ref: ${{ steps.getvars.outputs.version }}
          path: markbind

      - run: cd markbind && npm ci

      - name: Download zipped site
        run: wget -O ./site.zip ${{ steps.getvars.outputs.path }}

      - name: Unzip file
        uses: alyip98/unzip@v0.2-alpha
        with:
          file: ./site.zip
          path: ./site

      - name: Build site
        run: cd ./site && node markbind/index build --baseUrl ${{ env.BASE_URL }}

      - name: Archive Docs
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: site/_site

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            [Built site](${{ env.PAGES_URL }}/${{ github.sha }})

#      - name: Clone GH-Pages Repo with Access Token
#        run: git clone https://${{ secrets.PAGES_TOKEN }}@github.com/alyip98/GH-Actions-Test.git gh-pages
#
#      - name: Copy built files
#        run: cp -r site/_site gh-pages/${{ github.sha }}
#
#      - name: Create commit
#        run: cd gh-pages && git config user.email "" && git config user.name "GH Actions" && git add . && git commit -m "Update built site for ${{ github.sha }}\n ${{ env.PAGES_URL }}/${{ github.sha }}"
#
#      - name: Push to GH-Pages
#        run: cd gh-pages && git push
