name: Log info on pull request

on: [pull_request]

env:
  test: 123456

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Secrets
        env:
          GITHUB_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$GITHUB_CONTEXT"
