name: Build zip on issue comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout utilities
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/alyip98/GH-Actions-Test'
          path: 'util'

      - name: Print github event variable
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo "$EVENT"

      - name: Extract variables
        id: getvars
        uses: ./util/actions/extract-comment
        with:
          event: ${{ github.event }}

      - name: Print extracted variables
        run: echo ${{ steps.getvars.outputs }}

      - name: Checkout selected Markbind version
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/MarkBind/markbind'
          ref: ''
          path: 'markbind'



      - run: npm ci
