name: Build zip on issue comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print github event variable
        env:
          BODY: ${{ toJSON(github).event.comment.body }}
        run: echo "$BODY"

      - name: Checkout selected Markbind version
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/MarkBind/markbind.git'
          ref: ''

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm ci
